#!/bin/bash
set -e

APK_INPUT=$1
OUTPUT=$2
TEMP=$(mktemp -d)

aapt2 convert $APK_INPUT --output-format proto -o $TEMP/app_proto.apk


cd $TEMP

unzip app_proto.apk
mkdir manifest
mkdir dex
mv AndroidManifest.xml manifest/
mv classes.dex dex/
rm app_proto.apk

zip -r base.zip *

cd -

java -jar $BUNDLETOOL_PATH build-bundle --modules=$TEMP/base.zip --output=$OUTPUT
