name: Deploy Image

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/**.yml
      - Dockerfile

permissions:
  contents: read

jobs:
  deploy-docker:
    name: Docker Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - id: metadata
        run: |
          RUST_VERSION=$(cat ./Dockerfile | grep -oP 'rust:\K\d+\.\d+' | tr -d '.')
          echo "Rust Version: $RUST_VERSION"
          echo "rust_version=$RUST_VERSION" >> $GITHUB_OUTPUT

      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: network=host

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: sergioribera
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: sergioribera/rust-android:${{ steps.metadata.outputs.rust_version }}-sdk-33